networks: 
  cda-networks:
    driver: bridge

services:
  frontend-service:
    build: 
      context: ./frontend
      target: ${DOCKER_TARGET:-production}
    container_name: frontend-service
    restart: always
    ports:
      - "4000:80"     
    networks:
      - cda-networks
    environment: 
      VITE_PROJECT_SERVICE_URL: ${VITE_PROJECT_SERVICE_URL}
      VITE_AUTH_SERVICE_URL: ${VITE_AUTH_SERVICE_URL}
      VITE_CHAT_SERVICE_URL: ${VITE_CHAT_SERVICE_URL}
      VITE_PROJECT_USER_POST_SERVICE_URL: ${VITE_PROJECT_USER_POST_SERVICE_URL}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}          
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
    ports: 
      - "3000:80"
    networks:
      - cda-networks
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  project-service:
    build: 
      context: ./services/project-service
    container_name: project-service
    environment:
      DB_PORT: ${DB_PORT}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_DATABASE_PROJECT: ${DB_DATABASE_PROJECT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      VITE_AUTH_SERVICE_URL: ${VITE_AUTH_SERVICE_URL}
      PORT: ${PORT}
    ports: 
      - "3002:80"
    networks:
      - cda-networks
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  chat-service:
    build: 
      context: ./services/chat-service
    container_name: chat-service
    environment:
      DB_PORT: ${DB_PORT}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_DATABASE_CHAT: ${DB_DATABASE_CHAT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      VITE_AUTH_SERVICE_URL: ${VITE_AUTH_SERVICE_URL}
      VITE_PROJECT_SERVICE_URL: ${VITE_PROJECT_SERVICE_URL}
      PORT: ${PORT}
    ports: 
      - "3001:80"
    networks:
      - cda-networks
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  project-user-post-service:
    build: 
      context: ./services/project-user-post-service
    container_name: project-user-post-service
    environment:
      DB_PORT: ${DB_PORT}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_DATABASE_RELATION: ${DB_DATABASE_RELATION}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      VITE_AUTH_SERVICE_URL: ${VITE_AUTH_SERVICE_URL}
      VITE_PROJECT_SERVICE_URL: ${VITE_PROJECT_SERVICE_URL}
      VITE_CHAT_SERVICE_URL: ${VITE_CHAT_SERVICE_URL}
      PORT: ${PORT}
    ports: 
      - "3003:80"
    networks:
      - cda-networks
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
volumes:
  mysql_data: