CREATE DATABASE IF NOT EXISTS ${DB_DATABASE_CHAT};
CREATE DATABASE IF NOT EXISTS ${DB_DATABASE_PROJECT};

CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${DB_DATABASE_CHAT}.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON ${DB_DATABASE_PROJECT}.* TO '${MYSQL_USER}'@'%';

FLUSH PRIVILEGES;