#!/bin/bash
cat <<EOF > ./db/init.sql
CREATE DATABASE IF NOT EXISTS ${DB_DATABASE_PROJECT};
CREATE DATABASE IF NOT EXISTS ${DB_DATABASE_CHAT};

CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${DB_DATABASE_PROJECT}.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON ${DB_DATABASE_CHAT}.* TO '${MYSQL_USER}'@'%';

FLUSH PRIVILEGES;
EOF
